# Generated by Django 2.1.7 on 2019-02-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asdf', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
