# Generated by Django 2.1.7 on 2019-02-16 10:25

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0002_auto_20190216_1025'),
        ('cart', '0001_initial'),
        ('account', '0002_auto_20190216_1025'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('total_price', models.PositiveIntegerField()),
                ('shipping_address', models.CharField(max_length=256)),
                ('shipping_message', models.CharField(max_length=128, null=True)),
                ('contact_phone_num', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('owned_cart',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Cart')),
                ('owned_order',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('payment_complete', '결제 완료'), ('product_prepare', '상품 준비중'),
                                                     ('shipping_product', '상품 배송중'), ('shipping_complete', '배송 완료')],
                                            max_length=32)),
                ('date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='asdf',
        ),
    ]
